### ISSUE TITLE
Tracking total cost for gpt-3.5-turbo-0613 yields $0.0

### ISSUE THREAD

**Issue by TLazarevic** [hwchase17/langchain#6150]
### System Info

Langchain version: 0.0.200

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:

1. Create a ConversationChain instance with parameters:
```
llm = ChatOpenAI(model_name="gpt-3.5-turbo-0613", temperature=0)
memory = ConversationBufferMemory()
```
2. Run the chain inside callback block:
```
    with get_openai_callback() as cb:
            response = conversation.run("Tell me a joke")
            print(cb)
```
3. Total Cost is always $0.0.
<img width="767" alt="Screenshot 2023-06-14 at 11 31 21" src="https://github.com/hwchase17/langchain/assets/18078190/e7992bcb-f288-462f-ab2c-94d0d894929f">

### Expected behavior

Total cost of the conversation chain usage is reflected in the Total Cost parameter of the callback and represents accurate usage costs.

**Comment by jackskii** [comment]
you just used 90 tokens, that like $0.00018

**Comment by Potrock** [comment]
Same issue with GPT-4-0613. Should just need to update the openai callback info in langchain/callbacks

**Comment by TLazarevic** [comment]
@jackskii The example provided is for demonstration purposes, and still works with an older version of the model even with low usage costs.

**Comment by mheguy-stingray** [comment]
@TLazarevic: Can you please check if #6122 resolved your issue?

**Comment by TLazarevic** [comment]
@mheguy-stingray The cost is no longer zero. I'm not sure if the completion tokens are properly handled for the model here though.

**Comment by TLazarevic** [comment]
@mheguy-stingray I haven't looked into code much, but I can see that there are multiple prices listed for the models that have different prompt and completion prices (that would be gpt-4-32k and gpt-4-32k-completion for example, based on my assumption) and only a singular price for the new gpt 3.5-turbo-0613 even though OpenAI lists differing prompt/completion prices.

**Comment by mheguy-stingray** [comment]
@TLazarevic The current implementation definitely doesn't handle different prices for input and output tokens. You could/should create a feature request for that if one doesn't yet exist.

But if the bug described by your original ticket is resolved, you should close this ticket. :)

**Comment by TLazarevic** [comment]
@mheguy-stingray Well the costs aren't zero now, but they can't be correct then either. But I'll go ahead and close the issue.
